# Generated by Django 5.0.2 on 2024-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_atk', models.IntegerField()),
                ('stats_def', models.IntegerField()),
                ('Lskill_atk', models.IntegerField()),
                ('Lskill_def', models.IntegerField()),
                ('Pskill_atk_1', models.IntegerField()),
                ('Pskill_def_1', models.IntegerField()),
                ('Pskill_atk_2', models.IntegerField()),
                ('Pskill_def_2', models.IntegerField()),
                ('SA_atk', models.IntegerField()),
                ('SA_def', models.IntegerField()),
                ('ULSA_atl', models.IntegerField()),
                ('ULSA_def', models.IntegerField()),
                ('link_atk', models.IntegerField()),
                ('link_def', models.IntegerField()),
                ('SA_power', models.IntegerField()),
            ],
        ),
    ]
