# Generated by Django 5.0.2 on 2024-02-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatsForm',
            new_name='Stats',
        ),
    ]
