# Generated by Django 5.0.2 on 2024-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_statsform_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
